## Teamd rules

if $programname contains "teamd_" then {
    /var/log/teamd.log
    stop
}

## telemetry rules
if (($msg startswith  " telemetry") or ($msg startswith  " dialout" )) then {
    action(type="omfile" file="/var/log/telemetry.log" flushOnTXEnd="off" asyncWriting="on" flushInterval="5" ioBufferSize="64k")
    stop
}
