# name              lanes           alias          speed       mtu      fec    index
Ethernet0           241             Eth1/1         25000       9126     fc     0
Ethernet1           242             Eth1/2         25000       9126     fc     0
Ethernet2           243             Eth1/3         25000       9126     fc     0
Ethernet3           244             Eth1/4         25000       9126     fc     0
Ethernet8           249             Eth2/1         25000       9126     fc     1
Ethernet9           250             Eth2/2         25000       9126     fc     1
Ethernet10          251             Eth2/3         25000       9126     fc     1
Ethernet11          252             Eth2/4         25000       9126     fc     1
Ethernet16          233             Eth3/1         25000       9126     fc     2
Ethernet17          234             Eth3/2         25000       9126     fc     2
Ethernet18          235             Eth3/3         25000       9126     fc     2
Ethernet19          236             Eth3/4         25000       9126     fc     2
Ethernet24          225             Eth4/1         25000       9126     fc     3
Ethernet25          226             Eth4/2         25000       9126     fc     3
Ethernet26          227             Eth4/3         25000       9126     fc     3
Ethernet27          228             Eth4/4         25000       9126     fc     3
Ethernet32          217             Eth5/1         25000       9126     fc     4
Ethernet33          218             Eth5/2         25000       9126     fc     4
Ethernet34          219             Eth5/3         25000       9126     fc     4
Ethernet35          220             Eth5/4         25000       9126     fc     4
Ethernet40          209             Eth6/1         25000       9126     fc     5
Ethernet41          210             Eth6/2         25000       9126     fc     5
Ethernet42          211             Eth6/3         25000       9126     fc     5
Ethernet43          212             Eth6/4         25000       9126     fc     5
Ethernet48          201             Eth7/1         25000       9126     fc     6
Ethernet49          202             Eth7/2         25000       9126     fc     6
Ethernet50          203             Eth7/3         25000       9126     fc     6
Ethernet51          204             Eth7/4         25000       9126     fc     6
Ethernet56          193             Eth8/1         25000       9126     fc     7
Ethernet57          194             Eth8/2         25000       9126     fc     7
Ethernet58          195             Eth8/3         25000       9126     fc     7
Ethernet59          196             Eth8/4         25000       9126     fc     7
Ethernet64          185             Eth9/1         25000       9126     fc     8
Ethernet65          186             Eth9/2         25000       9126     fc     8
Ethernet66          187             Eth9/3         25000       9126     fc     8
Ethernet67          188             Eth9/4         25000       9126     fc     8
Ethernet72          177             Eth10/1        25000       9126     fc     9
Ethernet73          178             Eth10/2        25000       9126     fc     9
Ethernet74          179             Eth10/3        25000       9126     fc     9
Ethernet75          180             Eth10/4        25000       9126     fc     9
Ethernet80          169             Eth11/1        25000       9126     fc     10
Ethernet81          170             Eth11/2        25000       9126     fc     10
Ethernet82          171             Eth11/3        25000       9126     fc     10
Ethernet83          172             Eth11/4        25000       9126     fc     10
Ethernet88          161             Eth12/1        25000       9126     fc     11
Ethernet89          162             Eth12/2        25000       9126     fc     11
Ethernet90          163             Eth12/3        25000       9126     fc     11
Ethernet91          164             Eth12/4        25000       9126     fc     11
Ethernet96          153             Eth13/1        25000       9126     fc     12
Ethernet97          154             Eth13/2        25000       9126     fc     12
Ethernet98          155             Eth13/3        25000       9126     fc     12
Ethernet99          156             Eth13/4        25000       9126     fc     12
Ethernet104         145             Eth14/1        25000       9126     fc     13
Ethernet105         146             Eth14/2        25000       9126     fc     13
Ethernet106         147             Eth14/3        25000       9126     fc     13
Ethernet107         148             Eth14/4        25000       9126     fc     13
Ethernet112         137             Eth15/1        25000       9126     fc     14
Ethernet113         138             Eth15/2        25000       9126     fc     14
Ethernet114         139             Eth15/3        25000       9126     fc     14
Ethernet115         140             Eth15/4        25000       9126     fc     14
Ethernet120         121             Eth16/1        25000       9126     fc     15
Ethernet121         122             Eth16/2        25000       9126     fc     15
Ethernet122         123             Eth16/3        25000       9126     fc     15
Ethernet123         124             Eth16/4        25000       9126     fc     15
Ethernet128         129             Eth17/1        25000       9126     fc     16
Ethernet129         130             Eth17/2        25000       9126     fc     16
Ethernet130         131             Eth17/3        25000       9126     fc     16
Ethernet131         132             Eth17/4        25000       9126     fc     16
Ethernet136         113             Eth18/1        25000       9126     fc     17
Ethernet137         114             Eth18/2        25000       9126     fc     17
Ethernet138         115             Eth18/3        25000       9126     fc     17
Ethernet139         116             Eth18/4        25000       9126     fc     17
Ethernet144         105             Eth19/1        25000       9126     fc     18
Ethernet145         106             Eth19/2        25000       9126     fc     18
Ethernet146         107             Eth19/3        25000       9126     fc     18
Ethernet147         108             Eth19/4        25000       9126     fc     18
Ethernet152         97              Eth20/1        25000       9126     fc     19
Ethernet153         98              Eth20/2        25000       9126     fc     19
Ethernet154         99              Eth20/3        25000       9126     fc     19
Ethernet155         100             Eth20/4        25000       9126     fc     19
Ethernet160         89              Eth21/1        25000       9126     fc     20
Ethernet161         90              Eth21/2        25000       9126     fc     20
Ethernet162         91              Eth21/3        25000       9126     fc     20
Ethernet163         92              Eth21/4        25000       9126     fc     20
Ethernet168         81              Eth22/1        25000       9126     fc     21
Ethernet169         82              Eth22/2        25000       9126     fc     21
Ethernet170         83              Eth22/3        25000       9126     fc     21
Ethernet171         84              Eth22/4        25000       9126     fc     21
Ethernet176         73              Eth23/1        25000       9126     fc     22
Ethernet177         74              Eth23/2        25000       9126     fc     22
Ethernet178         75              Eth23/3        25000       9126     fc     22
Ethernet179         76              Eth23/4        25000       9126     fc     22
Ethernet184         65              Eth24/1        25000       9126     fc     23
Ethernet185         66              Eth24/2        25000       9126     fc     23
Ethernet186         67              Eth24/3        25000       9126     fc     23
Ethernet187         68              Eth24/4        25000       9126     fc     23
Ethernet192         57,58,59,60     Eth25/1        200000      9126     rs     24
Ethernet196         61,62,63,64     Eth25/2        200000      9126     rs     24
Ethernet200         49,50,51,52     Eth26/1        200000      9126     rs     25
Ethernet204         53,54,55,56     Eth26/2        200000      9126     rs     25
Ethernet208         41,42,43,44     Eth27/1        200000      9126     rs     26
Ethernet212         45,46,47,48     Eth27/2        200000      9126     rs     26
Ethernet216         33,34,35,36     Eth28/1        200000      9126     rs     27
Ethernet220         37,38,39,40     Eth28/2        200000      9126     rs     27
Ethernet224         25,26,27,28     Eth29/1        200000      9126     rs     28
Ethernet228         29,30,31,32     Eth29/2        200000      9126     rs     28
Ethernet232         17,18,19,20     Eth30/1        200000      9126     rs     29
Ethernet236         21,22,23,24     Eth30/2        200000      9126     rs     29
Ethernet240         9,10,11,12      Eth31/1        200000      9126     rs     30
Ethernet244         13,14,15,16     Eth31/2        200000      9126     rs     30
Ethernet248         1,2,3,4         Eth32/1        200000      9126     rs     31
Ethernet252         5,6,7,8         Eth32/2        200000      9126     rs     31
