# name              lanes           speed       mtu      fec    index
Ethernet0           241              25000      9126     fc     0
Ethernet1           242              25000      9126     fc     0
Ethernet2           243              25000      9126     fc     0
Ethernet3           244              25000      9126     fc     0
Ethernet8           249              25000      9126     fc     1
Ethernet9           250              25000      9126     fc     1
Ethernet10          251              25000      9126     fc     1
Ethernet11          252              25000      9126     fc     1
Ethernet16          233              25000      9126     fc     2
Ethernet17          234              25000      9126     fc     2
Ethernet18          235              25000      9126     fc     2
Ethernet19          236              25000      9126     fc     2
Ethernet24          225              25000      9126     fc     3
Ethernet25          226              25000      9126     fc     3
Ethernet26          227              25000      9126     fc     3
Ethernet27          228              25000      9126     fc     3
Ethernet32          217              25000      9126     fc     4
Ethernet33          218              25000      9126     fc     4
Ethernet34          219              25000      9126     fc     4
Ethernet35          220              25000      9126     fc     4
Ethernet40          209              25000      9126     fc     5
Ethernet41          210              25000      9126     fc     5
Ethernet42          211              25000      9126     fc     5
Ethernet43          212              25000      9126     fc     5
Ethernet48          201              25000      9126     fc     6
Ethernet49          202              25000      9126     fc     6
Ethernet50          203              25000      9126     fc     6
Ethernet51          204              25000      9126     fc     6
Ethernet56          193              25000      9126     fc     7
Ethernet57          194              25000      9126     fc     7
Ethernet58          195              25000      9126     fc     7
Ethernet59          196              25000      9126     fc     7
Ethernet64          185              25000      9126     fc     8
Ethernet65          186              25000      9126     fc     8
Ethernet66          187              25000      9126     fc     8
Ethernet67          188              25000      9126     fc     8
Ethernet72          177              25000      9126     fc     9
Ethernet73          178              25000      9126     fc     9
Ethernet74          179              25000      9126     fc     9
Ethernet75          180              25000      9126     fc     9
Ethernet80          169              25000      9126     fc     10
Ethernet81          170              25000      9126     fc     10
Ethernet82          171              25000      9126     fc     10
Ethernet83          172              25000      9126     fc     10
Ethernet88          161              25000      9126     fc     11
Ethernet89          162              25000      9126     fc     11
Ethernet90          163              25000      9126     fc     11
Ethernet91          164              25000      9126     fc     11
Ethernet96          153              25000      9126     fc     12
Ethernet97          154              25000      9126     fc     12
Ethernet98          155              25000      9126     fc     12
Ethernet99          156              25000      9126     fc     12
Ethernet104         145              25000      9126     fc     13
Ethernet105         146              25000      9126     fc     13
Ethernet106         147              25000      9126     fc     13
Ethernet107         148              25000      9126     fc     13
Ethernet112         137              25000      9126     fc     14
Ethernet113         138              25000      9126     fc     14
Ethernet114         139              25000      9126     fc     14
Ethernet115         140              25000      9126     fc     14
Ethernet120         121              25000      9126     fc     15
Ethernet121         122              25000      9126     fc     15
Ethernet122         123              25000      9126     fc     15
Ethernet123         124              25000      9126     fc     15
Ethernet128         129              25000      9126     fc     16
Ethernet129         130              25000      9126     fc     16
Ethernet130         131              25000      9126     fc     16
Ethernet131         132              25000      9126     fc     16
Ethernet136         113              25000      9126     fc     17
Ethernet137         114              25000      9126     fc     17
Ethernet138         115              25000      9126     fc     17
Ethernet139         116              25000      9126     fc     17
Ethernet144         105              25000      9126     fc     18
Ethernet145         106              25000      9126     fc     18
Ethernet146         107              25000      9126     fc     18
Ethernet147         108              25000      9126     fc     18
Ethernet152         97               25000      9126     fc     19
Ethernet153         98               25000      9126     fc     19
Ethernet154         99               25000      9126     fc     19
Ethernet155         100              25000      9126     fc     19
Ethernet160         89               25000      9126     fc     20
Ethernet161         90               25000      9126     fc     20
Ethernet162         91               25000      9126     fc     20
Ethernet163         92               25000      9126     fc     20
Ethernet168         81               25000      9126     fc     21
Ethernet169         82               25000      9126     fc     21
Ethernet170         83               25000      9126     fc     21
Ethernet171         84               25000      9126     fc     21
Ethernet176         73               25000      9126     fc     22
Ethernet177         74               25000      9126     fc     22
Ethernet178         75               25000      9126     fc     22
Ethernet179         76               25000      9126     fc     22
Ethernet184         65               25000      9126     fc     23
Ethernet185         66               25000      9126     fc     23
Ethernet186         67               25000      9126     fc     23
Ethernet187         68               25000      9126     fc     23
Ethernet192         57,58,59,60     200000      9126     rs     24
Ethernet196         61,62,63,64     200000      9126     rs     24
Ethernet200         49,50,51,52     200000      9126     rs     25
Ethernet204         53,54,55,56     200000      9126     rs     25
Ethernet208         41,42,43,44     200000      9126     rs     26
Ethernet212         45,46,47,48     200000      9126     rs     26
Ethernet216         33,34,35,36     200000      9126     rs     27
Ethernet220         37,38,39,40     200000      9126     rs     27
Ethernet224         25,26,27,28     200000      9126     rs     28
Ethernet228         29,30,31,32     200000      9126     rs     28
Ethernet232         17,18,19,20     200000      9126     rs     29
Ethernet236         21,22,23,24     200000      9126     rs     29
Ethernet240         9,10,11,12      200000      9126     rs     30
Ethernet244         13,14,15,16     200000      9126     rs     30
Ethernet248         1,2,3,4         200000      9126     rs     31
Ethernet252         5,6,7,8         200000      9126     rs     31
