ifcs:
  options:
    log_level: "info"
nodes:
- node_id: "0"
  options:
    sku: "innovium.77700_B"
    buffer_management_mode: "api_driven"
    pt01: "768"
    wred_cr_ip_proto_list: "17"
    cr_assignment_mode: "1"
    max_lossless_tc: "2"
    sd_low_power_mode_global_default: "true"
    ecn_stats_enable: "1"
    forward_profile: "IFCS_FORWARD_PROFILE_ID_PROFILE_E"
    ilpm_enable: "1"
    srp2: "126"
    netdev:
    - auto_create: "no"
      multi_interface: "yes"
    mac_clk: "1340"
    sys_clk: "1720"
    ifc_clk: "1200"
    skip_pll_check: "true"
    mbist_on_init: "true"
    txring:
    - txring_id: "0"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "1"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "2"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "3"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    rxring:
    - rxring_id: "0"
      desc_count: "1024"
      prio: "1"
      queues: "0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44"
      netdev: "true"
    - rxring_id: "1"
      desc_count: "1024"
      prio: "1"
      queues: "1, 5, 9, 13, 17, 21, 25, 29, 33, 37, 41, 45"
      netdev: "true"
    - rxring_id: "2"
      desc_count: "1024"
      prio: "1"
      queues: "2, 6, 10, 14, 18, 22, 26, 30, 34, 38, 42, 46"
      netdev: "true"
    - rxring_id: "3"
      desc_count: "1024"
      prio: "1"
      queues: "3, 7, 11, 15, 19, 23, 27, 31, 35, 39, 43, 47"
      netdev: "true"
  devports:
  - id: "0"
    sysport: "1000"
    type: "cpu"
  - fec: "FCFEC"
    id: "241"
    lanes: "0:1"
    serdes_group: "30"
    speed: "25G"
    sysport: "241"
    type: "eth"
  - fec: "FCFEC"
    id: "242"
    lanes: "1:1"
    serdes_group: "30"
    speed: "25G"
    sysport: "242"
    type: "eth"
  - fec: "FCFEC"
    id: "243"
    lanes: "2:1"
    serdes_group: "30"
    speed: "25G"
    sysport: "243"
    type: "eth"
  - fec: "FCFEC"
    id: "244"
    lanes: "3:1"
    serdes_group: "30"
    speed: "25G"
    sysport: "244"
    type: "eth"
  - fec: "FCFEC"
    id: "249"
    lanes: "0:1"
    serdes_group: "31"
    speed: "25G"
    sysport: "249"
    type: "eth"
  - fec: "FCFEC"
    id: "250"
    lanes: "1:1"
    serdes_group: "31"
    speed: "25G"
    sysport: "250"
    type: "eth"
  - fec: "FCFEC"
    id: "251"
    lanes: "2:1"
    serdes_group: "31"
    speed: "25G"
    sysport: "251"
    type: "eth"
  - fec: "FCFEC"
    id: "252"
    lanes: "3:1"
    serdes_group: "31"
    speed: "25G"
    sysport: "252"
    type: "eth"
  - fec: "FCFEC"
    id: "233"
    lanes: "0:1"
    serdes_group: "29"
    speed: "25G"
    sysport: "233"
    type: "eth"
  - fec: "FCFEC"
    id: "234"
    lanes: "1:1"
    serdes_group: "29"
    speed: "25G"
    sysport: "234"
    type: "eth"
  - fec: "FCFEC"
    id: "235"
    lanes: "2:1"
    serdes_group: "29"
    speed: "25G"
    sysport: "235"
    type: "eth"
  - fec: "FCFEC"
    id: "236"
    lanes: "3:1"
    serdes_group: "29"
    speed: "25G"
    sysport: "236"
    type: "eth"
  - fec: "FCFEC"
    id: "225"
    lanes: "0:1"
    serdes_group: "28"
    speed: "25G"
    sysport: "225"
    type: "eth"
  - fec: "FCFEC"
    id: "226"
    lanes: "1:1"
    serdes_group: "28"
    speed: "25G"
    sysport: "226"
    type: "eth"
  - fec: "FCFEC"
    id: "227"
    lanes: "2:1"
    serdes_group: "28"
    speed: "25G"
    sysport: "227"
    type: "eth"
  - fec: "FCFEC"
    id: "228"
    lanes: "3:1"
    serdes_group: "28"
    speed: "25G"
    sysport: "228"
    type: "eth"
  - fec: "FCFEC"
    id: "217"
    lanes: "0:1"
    serdes_group: "27"
    speed: "25G"
    sysport: "217"
    type: "eth"
  - fec: "FCFEC"
    id: "218"
    lanes: "1:1"
    serdes_group: "27"
    speed: "25G"
    sysport: "218"
    type: "eth"
  - fec: "FCFEC"
    id: "219"
    lanes: "2:1"
    serdes_group: "27"
    speed: "25G"
    sysport: "219"
    type: "eth"
  - fec: "FCFEC"
    id: "220"
    lanes: "3:1"
    serdes_group: "27"
    speed: "25G"
    sysport: "220"
    type: "eth"
  - fec: "FCFEC"
    id: "209"
    lanes: "0:1"
    serdes_group: "26"
    speed: "25G"
    sysport: "209"
    type: "eth"
  - fec: "FCFEC"
    id: "210"
    lanes: "1:1"
    serdes_group: "26"
    speed: "25G"
    sysport: "210"
    type: "eth"
  - fec: "FCFEC"
    id: "211"
    lanes: "2:1"
    serdes_group: "26"
    speed: "25G"
    sysport: "211"
    type: "eth"
  - fec: "FCFEC"
    id: "212"
    lanes: "3:1"
    serdes_group: "26"
    speed: "25G"
    sysport: "212"
    type: "eth"
  - fec: "FCFEC"
    id: "201"
    lanes: "0:1"
    serdes_group: "25"
    speed: "25G"
    sysport: "201"
    type: "eth"
  - fec: "FCFEC"
    id: "202"
    lanes: "1:1"
    serdes_group: "25"
    speed: "25G"
    sysport: "202"
    type: "eth"
  - fec: "FCFEC"
    id: "203"
    lanes: "2:1"
    serdes_group: "25"
    speed: "25G"
    sysport: "203"
    type: "eth"
  - fec: "FCFEC"
    id: "204"
    lanes: "3:1"
    serdes_group: "25"
    speed: "25G"
    sysport: "204"
    type: "eth"
  - fec: "FCFEC"
    id: "193"
    lanes: "0:1"
    serdes_group: "24"
    speed: "25G"
    sysport: "193"
    type: "eth"
  - fec: "FCFEC"
    id: "194"
    lanes: "1:1"
    serdes_group: "24"
    speed: "25G"
    sysport: "194"
    type: "eth"
  - fec: "FCFEC"
    id: "195"
    lanes: "2:1"
    serdes_group: "24"
    speed: "25G"
    sysport: "195"
    type: "eth"
  - fec: "FCFEC"
    id: "196"
    lanes: "3:1"
    serdes_group: "24"
    speed: "25G"
    sysport: "196"
    type: "eth"
  - fec: "FCFEC"
    id: "185"
    lanes: "0:1"
    serdes_group: "23"
    speed: "25G"
    sysport: "185"
    type: "eth"
  - fec: "FCFEC"
    id: "186"
    lanes: "1:1"
    serdes_group: "23"
    speed: "25G"
    sysport: "186"
    type: "eth"
  - fec: "FCFEC"
    id: "187"
    lanes: "2:1"
    serdes_group: "23"
    speed: "25G"
    sysport: "187"
    type: "eth"
  - fec: "FCFEC"
    id: "188"
    lanes: "3:1"
    serdes_group: "23"
    speed: "25G"
    sysport: "188"
    type: "eth"
  - fec: "FCFEC"
    id: "177"
    lanes: "0:1"
    serdes_group: "22"
    speed: "25G"
    sysport: "177"
    type: "eth"
  - fec: "FCFEC"
    id: "178"
    lanes: "1:1"
    serdes_group: "22"
    speed: "25G"
    sysport: "178"
    type: "eth"
  - fec: "FCFEC"
    id: "179"
    lanes: "2:1"
    serdes_group: "22"
    speed: "25G"
    sysport: "179"
    type: "eth"
  - fec: "FCFEC"
    id: "180"
    lanes: "3:1"
    serdes_group: "22"
    speed: "25G"
    sysport: "180"
    type: "eth"
  - fec: "FCFEC"
    id: "169"
    lanes: "0:1"
    serdes_group: "21"
    speed: "25G"
    sysport: "169"
    type: "eth"
  - fec: "FCFEC"
    id: "170"
    lanes: "1:1"
    serdes_group: "21"
    speed: "25G"
    sysport: "170"
    type: "eth"
  - fec: "FCFEC"
    id: "171"
    lanes: "2:1"
    serdes_group: "21"
    speed: "25G"
    sysport: "171"
    type: "eth"
  - fec: "FCFEC"
    id: "172"
    lanes: "3:1"
    serdes_group: "21"
    speed: "25G"
    sysport: "172"
    type: "eth"
  - fec: "FCFEC"
    id: "161"
    lanes: "0:1"
    serdes_group: "20"
    speed: "25G"
    sysport: "161"
    type: "eth"
  - fec: "FCFEC"
    id: "162"
    lanes: "1:1"
    serdes_group: "20"
    speed: "25G"
    sysport: "162"
    type: "eth"
  - fec: "FCFEC"
    id: "163"
    lanes: "2:1"
    serdes_group: "20"
    speed: "25G"
    sysport: "163"
    type: "eth"
  - fec: "FCFEC"
    id: "164"
    lanes: "3:1"
    serdes_group: "20"
    speed: "25G"
    sysport: "164"
    type: "eth"
  - fec: "FCFEC"
    id: "153"
    lanes: "0:1"
    serdes_group: "19"
    speed: "25G"
    sysport: "153"
    type: "eth"
  - fec: "FCFEC"
    id: "154"
    lanes: "1:1"
    serdes_group: "19"
    speed: "25G"
    sysport: "154"
    type: "eth"
  - fec: "FCFEC"
    id: "155"
    lanes: "2:1"
    serdes_group: "19"
    speed: "25G"
    sysport: "155"
    type: "eth"
  - fec: "FCFEC"
    id: "156"
    lanes: "3:1"
    serdes_group: "19"
    speed: "25G"
    sysport: "156"
    type: "eth"
  - fec: "FCFEC"
    id: "145"
    lanes: "0:1"
    serdes_group: "18"
    speed: "25G"
    sysport: "145"
    type: "eth"
  - fec: "FCFEC"
    id: "146"
    lanes: "1:1"
    serdes_group: "18"
    speed: "25G"
    sysport: "146"
    type: "eth"
  - fec: "FCFEC"
    id: "147"
    lanes: "2:1"
    serdes_group: "18"
    speed: "25G"
    sysport: "147"
    type: "eth"
  - fec: "FCFEC"
    id: "148"
    lanes: "3:1"
    serdes_group: "18"
    speed: "25G"
    sysport: "148"
    type: "eth"
  - fec: "FCFEC"
    id: "137"
    lanes: "0:1"
    serdes_group: "17"
    speed: "25G"
    sysport: "137"
    type: "eth"
  - fec: "FCFEC"
    id: "138"
    lanes: "1:1"
    serdes_group: "17"
    speed: "25G"
    sysport: "138"
    type: "eth"
  - fec: "FCFEC"
    id: "139"
    lanes: "2:1"
    serdes_group: "17"
    speed: "25G"
    sysport: "139"
    type: "eth"
  - fec: "FCFEC"
    id: "140"
    lanes: "3:1"
    serdes_group: "17"
    speed: "25G"
    sysport: "140"
    type: "eth"
  - fec: "FCFEC"
    id: "121"
    lanes: "0:1"
    serdes_group: "15"
    speed: "25G"
    sysport: "121"
    type: "eth"
  - fec: "FCFEC"
    id: "122"
    lanes: "1:1"
    serdes_group: "15"
    speed: "25G"
    sysport: "122"
    type: "eth"
  - fec: "FCFEC"
    id: "123"
    lanes: "2:1"
    serdes_group: "15"
    speed: "25G"
    sysport: "123"
    type: "eth"
  - fec: "FCFEC"
    id: "124"
    lanes: "3:1"
    serdes_group: "15"
    speed: "25G"
    sysport: "124"
    type: "eth"
  - fec: "FCFEC"
    id: "129"
    lanes: "0:1"
    serdes_group: "16"
    speed: "25G"
    sysport: "129"
    type: "eth"
  - fec: "FCFEC"
    id: "130"
    lanes: "1:1"
    serdes_group: "16"
    speed: "25G"
    sysport: "130"
    type: "eth"
  - fec: "FCFEC"
    id: "131"
    lanes: "2:1"
    serdes_group: "16"
    speed: "25G"
    sysport: "131"
    type: "eth"
  - fec: "FCFEC"
    id: "132"
    lanes: "3:1"
    serdes_group: "16"
    speed: "25G"
    sysport: "132"
    type: "eth"
  - fec: "FCFEC"
    id: "113"
    lanes: "0:1"
    serdes_group: "14"
    speed: "25G"
    sysport: "113"
    type: "eth"
  - fec: "FCFEC"
    id: "114"
    lanes: "1:1"
    serdes_group: "14"
    speed: "25G"
    sysport: "114"
    type: "eth"
  - fec: "FCFEC"
    id: "115"
    lanes: "2:1"
    serdes_group: "14"
    speed: "25G"
    sysport: "115"
    type: "eth"
  - fec: "FCFEC"
    id: "116"
    lanes: "3:1"
    serdes_group: "14"
    speed: "25G"
    sysport: "116"
    type: "eth"
  - fec: "FCFEC"
    id: "105"
    lanes: "0:1"
    serdes_group: "13"
    speed: "25G"
    sysport: "105"
    type: "eth"
  - fec: "FCFEC"
    id: "106"
    lanes: "1:1"
    serdes_group: "13"
    speed: "25G"
    sysport: "106"
    type: "eth"
  - fec: "FCFEC"
    id: "107"
    lanes: "2:1"
    serdes_group: "13"
    speed: "25G"
    sysport: "107"
    type: "eth"
  - fec: "FCFEC"
    id: "108"
    lanes: "3:1"
    serdes_group: "13"
    speed: "25G"
    sysport: "108"
    type: "eth"
  - fec: "FCFEC"
    id: "97"
    lanes: "0:1"
    serdes_group: "12"
    speed: "25G"
    sysport: "97"
    type: "eth"
  - fec: "FCFEC"
    id: "98"
    lanes: "1:1"
    serdes_group: "12"
    speed: "25G"
    sysport: "98"
    type: "eth"
  - fec: "FCFEC"
    id: "99"
    lanes: "2:1"
    serdes_group: "12"
    speed: "25G"
    sysport: "99"
    type: "eth"
  - fec: "FCFEC"
    id: "100"
    lanes: "3:1"
    serdes_group: "12"
    speed: "25G"
    sysport: "100"
    type: "eth"
  - fec: "FCFEC"
    id: "89"
    lanes: "0:1"
    serdes_group: "11"
    speed: "25G"
    sysport: "89"
    type: "eth"
  - fec: "FCFEC"
    id: "90"
    lanes: "1:1"
    serdes_group: "11"
    speed: "25G"
    sysport: "90"
    type: "eth"
  - fec: "FCFEC"
    id: "91"
    lanes: "2:1"
    serdes_group: "11"
    speed: "25G"
    sysport: "91"
    type: "eth"
  - fec: "FCFEC"
    id: "92"
    lanes: "3:1"
    serdes_group: "11"
    speed: "25G"
    sysport: "92"
    type: "eth"
  - fec: "FCFEC"
    id: "81"
    lanes: "0:1"
    serdes_group: "10"
    speed: "25G"
    sysport: "81"
    type: "eth"
  - fec: "FCFEC"
    id: "82"
    lanes: "1:1"
    serdes_group: "10"
    speed: "25G"
    sysport: "82"
    type: "eth"
  - fec: "FCFEC"
    id: "83"
    lanes: "2:1"
    serdes_group: "10"
    speed: "25G"
    sysport: "83"
    type: "eth"
  - fec: "FCFEC"
    id: "84"
    lanes: "3:1"
    serdes_group: "10"
    speed: "25G"
    sysport: "84"
    type: "eth"
  - fec: "FCFEC"
    id: "73"
    lanes: "0:1"
    serdes_group: "9"
    speed: "25G"
    sysport: "73"
    type: "eth"
  - fec: "FCFEC"
    id: "74"
    lanes: "1:1"
    serdes_group: "9"
    speed: "25G"
    sysport: "74"
    type: "eth"
  - fec: "FCFEC"
    id: "75"
    lanes: "2:1"
    serdes_group: "9"
    speed: "25G"
    sysport: "75"
    type: "eth"
  - fec: "FCFEC"
    id: "76"
    lanes: "3:1"
    serdes_group: "9"
    speed: "25G"
    sysport: "76"
    type: "eth"
  - fec: "FCFEC"
    id: "65"
    lanes: "0:1"
    serdes_group: "8"
    speed: "25G"
    sysport: "65"
    type: "eth"
  - fec: "FCFEC"
    id: "66"
    lanes: "1:1"
    serdes_group: "8"
    speed: "25G"
    sysport: "66"
    type: "eth"
  - fec: "FCFEC"
    id: "67"
    lanes: "2:1"
    serdes_group: "8"
    speed: "25G"
    sysport: "67"
    type: "eth"
  - fec: "FCFEC"
    id: "68"
    lanes: "3:1"
    serdes_group: "8"
    speed: "25G"
    sysport: "68"
    type: "eth"
  - fec: "KPFEC"
    id: "57"
    lanes: "0:4"
    serdes_group: "7"
    speed: "200G"
    sysport: "57"
    type: "eth"
  - fec: "KPFEC"
    id: "61"
    lanes: "4:4"
    serdes_group: "7"
    speed: "200G"
    sysport: "61"
    type: "eth"
  - fec: "KPFEC"
    id: "49"
    lanes: "0:4"
    serdes_group: "6"
    speed: "200G"
    sysport: "49"
    type: "eth"
  - fec: "KPFEC"
    id: "53"
    lanes: "4:4"
    serdes_group: "6"
    speed: "200G"
    sysport: "53"
    type: "eth"
  - fec: "KPFEC"
    id: "41"
    lanes: "0:4"
    serdes_group: "5"
    speed: "200G"
    sysport: "41"
    type: "eth"
  - fec: "KPFEC"
    id: "45"
    lanes: "4:4"
    serdes_group: "5"
    speed: "200G"
    sysport: "45"
    type: "eth"
  - fec: "KPFEC"
    id: "33"
    lanes: "0:4"
    serdes_group: "4"
    speed: "200G"
    sysport: "33"
    type: "eth"
  - fec: "KPFEC"
    id: "37"
    lanes: "4:4"
    serdes_group: "4"
    speed: "200G"
    sysport: "37"
    type: "eth"
  - fec: "KPFEC"
    id: "25"
    lanes: "0:4"
    serdes_group: "3"
    speed: "200G"
    sysport: "25"
    type: "eth"
  - fec: "KPFEC"
    id: "29"
    lanes: "4:4"
    serdes_group: "3"
    speed: "200G"
    sysport: "29"
    type: "eth"
  - fec: "KPFEC"
    id: "17"
    lanes: "0:4"
    serdes_group: "2"
    speed: "200G"
    sysport: "17"
    type: "eth"
  - fec: "KPFEC"
    id: "21"
    lanes: "4:4"
    serdes_group: "2"
    speed: "200G"
    sysport: "21"
    type: "eth"
  - fec: "KPFEC"
    id: "9"
    lanes: "0:4"
    serdes_group: "1"
    speed: "200G"
    sysport: "9"
    type: "eth"
  - fec: "KPFEC"
    id: "13"
    lanes: "4:4"
    serdes_group: "1"
    speed: "200G"
    sysport: "13"
    type: "eth"
  - fec: "KPFEC"
    id: "1"
    lanes: "0:4"
    serdes_group: "0"
    speed: "200G"
    sysport: "1"
    type: "eth"
  - fec: "KPFEC"
    id: "5"
    lanes: "4:4"
    serdes_group: "0"
    speed: "200G"
    sysport: "5"
    type: "eth"
  isg:
  - id: "0"
    tx_polarity: "00000000"
    rx_polarity: "00000000"
    lane_swap: "64752031"
  - id: "1"
    tx_polarity: "00000000"
    rx_polarity: "00000000"
    lane_swap: "64752031"
  - id: "2"
    tx_polarity: "00000000"
    rx_polarity: "00000000"
    lane_swap: "64752301"
  - id: "3"
    tx_polarity: "00000000"
    rx_polarity: "00000000"
    lane_swap: "74653021"
  - id: "4"
    tx_polarity: "00000000"
    rx_polarity: "00000000"
    lane_swap: "74653021"
  - id: "5"
    tx_polarity: "00000000"
    rx_polarity: "00000000"
    lane_swap: "74653021"
  - id: "6"
    tx_polarity: "00000111"
    rx_polarity: "11001101"
    lane_swap: "30472156"
  - id: "7"
    tx_polarity: "00001001"
    rx_polarity: "01001001"
    lane_swap: "05271436"
  - id: "8"
    tx_polarity: "00000011"
    rx_polarity: "11001100"
    lane_swap: "30472156"
  - id: "9"
    tx_polarity: "10001011"
    rx_polarity: "01001101"
    lane_swap: "05271436"
  - id: "10"
    tx_polarity: "00111111"
    rx_polarity: "11101001"
    lane_swap: "30472156"
  - id: "11"
    tx_polarity: "10111010"
    rx_polarity: "00010110"
    lane_swap: "05271436"
  - id: "12"
    tx_polarity: "01000001"
    rx_polarity: "11010100"
    lane_swap: "30472156"
  - id: "13"
    tx_polarity: "11001001"
    rx_polarity: "01001010"
    lane_swap: "37164520"
  - id: "14"
    tx_polarity: "00000000"
    rx_polarity: "01100111"
    lane_swap: "30472156"
  - id: "15"
    tx_polarity: "00000001"
    rx_polarity: "00001100"
    lane_swap: "30472156"
  - id: "16"
    tx_polarity: "01111111"
    rx_polarity: "00010000"
    lane_swap: "47305621"
  - id: "17"
    tx_polarity: "00001110"
    rx_polarity: "11101101"
    lane_swap: "05271436"
  - id: "18"
    tx_polarity: "00001011"
    rx_polarity: "00001000"
    lane_swap: "30472156"
  - id: "19"
    tx_polarity: "00100010"
    rx_polarity: "01110101"
    lane_swap: "03651274"
  - id: "20"
    tx_polarity: "00010000"
    rx_polarity: "01000001"
    lane_swap: "30472156"
  - id: "21"
    tx_polarity: "00101000"
    rx_polarity: "10010010"
    lane_swap: "31452067"
  - id: "22"
    tx_polarity: "00000000"
    rx_polarity: "10000000"
    lane_swap: "30472156"
  - id: "23"
    tx_polarity: "10001010"
    rx_polarity: "00011001"
    lane_swap: "07251436"
  - id: "24"
    tx_polarity: "00000000"
    rx_polarity: "10111011"
    lane_swap: "30472156"
  - id: "25"
    tx_polarity: "11101001"
    rx_polarity: "00001000"
    lane_swap: "05271436"
  - id: "26"
    tx_polarity: "00000000"
    rx_polarity: "00000000"
    lane_swap: "74563012"
  - id: "27"
    tx_polarity: "00000000"
    rx_polarity: "00000000"
    lane_swap: "75643012"
  - id: "28"
    tx_polarity: "00000000"
    rx_polarity: "00000000"
    lane_swap: "74653021"
  - id: "29"
    tx_polarity: "00000000"
    rx_polarity: "00000000"
    lane_swap: "74563021"
  - id: "30"
    tx_polarity: "00000000"
    rx_polarity: "00000000"
    lane_swap: "75643120"
  - id: "31"
    tx_polarity: "00000000"
    rx_polarity: "00000000"
    lane_swap: "74653021"
  - id: "32"
    tx_polarity: "00000000"
    rx_polarity: "00000000"
    lane_swap: "01234567"
