#!/usr/bin/python

"""
    sonic-metrics
    metrics update daemon for SONiC
"""

try:
    import os
    import signal
    import string
    import sys
    import threading
    import time
    import syslog

    from swsssdk import SonicV2Connector
    from metrics.process_metrics import ProcessInfoUpdateTask
    from metrics.system_metrics import SystemInfoUpdateTask
    from metrics.logger import Logger

except ImportError as e:
    raise ImportError(str(e) + " - required module not found")

#
# Constants ====================================================================
#

SYSLOG_IDENTIFIER = "sonic_metricsd"
log = Logger(SYSLOG_IDENTIFIER)

REDIS_HOSTNAME = "localhost"
REDIS_PORT = 6379
REDIS_TIMEOUT_MSECS = 0
METRICSD_MAIN_THREAD_SLEEP_SECS = 60

#
# Daemon =======================================================================
#
class DaemonMetricsd():
    """
    A daemon that run as a service to collect metrics with a configurable interval
    and store the check result to redis.
    """
    def __init__(self):
        """
        Constructor of DaemonMetricsd.
        """
        # Connect to STATE_DB and create system and process info tables
        self._db = SonicV2Connector(host='127.0.0.1')
        self._db.connect(self._db.STATE_DB)

        self.timeout = METRICSD_MAIN_THREAD_SLEEP_SECS
        self.stop_event = threading.Event()

        # Register our default signal handlers, unless the signal already has a
        # handler registered, most likely from a subclass implementation
        if not signal.getsignal(signal.SIGHUP):
            signal.signal(signal.SIGHUP, self.signal_handler)
        if not signal.getsignal(signal.SIGINT):
            signal.signal(signal.SIGINT, self.signal_handler)
        if not signal.getsignal(signal.SIGTERM):
            signal.signal(signal.SIGTERM, self.signal_handler)


    # Signal handler
    def signal_handler(self, sig, frame):
        if sig == signal.SIGHUP:
            log.info("Caught SIGHUP - ignoring...")
        elif sig == signal.SIGINT:
            log.info("Caught SIGINT - exiting...")
            self.stop_event.set()
        elif sig == signal.SIGTERM:
            log.info("Caught SIGTERM - exiting...")
            self.stop_event.set()
        else:
            log.info("Caught unhandled signal '" + sig + "'")


    # Initialize daemon
    def init(self):
        log.info("Start daemon init...")


    # Remove all entries in 'SYSTEM_INFO' table.
    def _clear_system_info_table(self):
        self._db.delete_all_by_pattern(self._db.STATE_DB, "SYSTEM_INFO|*")


    # Remove all entries in 'PROCESS_INFO' table.
    def _clear_process_info_table(self):
        self._db.delete_all_by_pattern(self._db.STATE_DB, "PROCESS_INFO|*")


    # Deinitialize daemon
    def deinit(self):
        """
        Destructor. Remove all entries in 'PROCESS_INFO' and 'SYSTEM_INFO' table.
        :return:
        """
        log.info("Start daemon deinit...")
        self._clear_system_info_table()
        self._clear_process_info_table()


    def process_data(self):
        #TBD
        return

    # Run daemon
    def run(self):
        log.info("Starting up...")

        # Start daemon initialization sequence
        self.init()

        # Start syslog info update thread

        # Start process info update thread
        process_info_update = ProcessInfoUpdateTask()
        process_info_update.task_run(self._db)

        # Start system info update thread
        system_info_update = SystemInfoUpdateTask()
        system_info_update.task_run(self._db)

        # Start main loop
        log.info("Start daemon main loop")

        while not self.stop_event.wait(self.timeout):
           self.process_data()

        log.info("Stop daemon main loop")

        # Stop process info update thread
        process_info_update.task_stop()

        # Stop system info update thread
        system_info_update.task_stop()

        # Start daemon deinitialization sequence
        self.deinit()
        self._db.close(self._db.STATE_DB)

        log.info("Shutting down...")

#
# Main =========================================================================
#

# This is our main entry point for sonic-metricsd script
def main():
    log.set_priority_info()
    metricsd = DaemonMetricsd()
    metricsd.run()


if __name__ == '__main__':
    main()
