IFCS_INIT_FILE : "/usr/share/sonic/hwsku/utopias_p3b.config.yaml"
IFCS_SKU_FILE : "/usr/share/sonic/hwsku/innovium.77700_A"
IFCS_INNO_CLI_PORT : "9999"
IFCS_TARGET : "device"
ULIMIT : "65536"
INNOVIUM_DIR : "/innovium"
PYTHONPATH : "$INNOVIUM_DIR:$INNOVIUM_DIR/cmds:$INNOVIUM_DIR/scripts:$INNOVIUM_DIR/test/:$INNOVIUM_DIR/test/utils:$INNOVIUM_DIR/utils:$INNOVIUM_DIR/pyctypes"
PLATFORM_LIBRARY : "/usr/lib/libinn_intf.so"
AVG_IPG_RESERVED_SIZE: "1518"
AVG_QUEUE_RESERVED_SIZE: "1518"
