ifcs:
  options:
    log_level: "info"
nodes:
- node_id: "0"
  options:
    sku: "innovium.77700_A"
    buffer_management_mode: "api_driven"
    max_lossless_tc: "2"
    forward_profile: "IFCS_FORWARD_PROFILE_ID_PROFILE_E"
    wred_cr_ip_proto_list: "17"
    netdev:
    - auto_create: "no"
      multi_interface: "yes"
    mac_clk: "1340"
    sys_clk: "1720"
    ifc_clk: "1200"
    skip_pll_check: "true"
    mbist_on_init: "true"
    txring:
    - txring_id: "0"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "1"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "2"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "3"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    rxring:
    - rxring_id: "0"
      desc_count: "1024"
      prio: "1"
      queues: "0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44"
      netdev: "true"
    - rxring_id: "1"
      desc_count: "1024"
      prio: "1"
      queues: "1, 5, 9, 13, 17, 21, 25, 29, 33, 37, 41, 45"
      netdev: "true"
    - rxring_id: "2"
      desc_count: "1024"
      prio: "1"
      queues: "2, 6, 10, 14, 18, 22, 26, 30, 34, 38, 42, 46"
      netdev: "true"
    - rxring_id: "3"
      desc_count: "1024"
      prio: "1"
      queues: "3, 7, 11, 15, 19, 23, 27, 31, 35, 39, 43, 47"
      netdev: "true"
  devports:
  - id: "0"
    sysport: "1000"
    type: "cpu"
  - fec: "KPFEC"
    id: "241"
    lanes: "0:8"
    serdes_group: "30"
    speed: "400G"
    sysport: "241"
    type: "eth"
  - fec: "KPFEC"
    id: "249"
    lanes: "0:8"
    serdes_group: "31"
    speed: "400G"
    sysport: "249"
    type: "eth"
  - fec: "KPFEC"
    id: "233"
    lanes: "0:8"
    serdes_group: "29"
    speed: "400G"
    sysport: "233"
    type: "eth"
  - fec: "KPFEC"
    id: "225"
    lanes: "0:8"
    serdes_group: "28"
    speed: "400G"
    sysport: "225"
    type: "eth"
  - fec: "KPFEC"
    id: "217"
    lanes: "0:8"
    serdes_group: "27"
    speed: "400G"
    sysport: "217"
    type: "eth"
  - fec: "KPFEC"
    id: "209"
    lanes: "0:8"
    serdes_group: "26"
    speed: "400G"
    sysport: "209"
    type: "eth"
  - fec: "KPFEC"
    id: "201"
    lanes: "0:8"
    serdes_group: "25"
    speed: "400G"
    sysport: "201"
    type: "eth"
  - fec: "KPFEC"
    id: "193"
    lanes: "0:8"
    serdes_group: "24"
    speed: "400G"
    sysport: "193"
    type: "eth"
  - fec: "KPFEC"
    id: "185"
    lanes: "0:8"
    serdes_group: "23"
    speed: "400G"
    sysport: "185"
    type: "eth"
  - fec: "KPFEC"
    id: "177"
    lanes: "0:8"
    serdes_group: "22"
    speed: "400G"
    sysport: "177"
    type: "eth"
  - fec: "KPFEC"
    id: "169"
    lanes: "0:8"
    serdes_group: "21"
    speed: "400G"
    sysport: "169"
    type: "eth"
  - fec: "KPFEC"
    id: "161"
    lanes: "0:8"
    serdes_group: "20"
    speed: "400G"
    sysport: "161"
    type: "eth"
  - fec: "KPFEC"
    id: "153"
    lanes: "0:8"
    serdes_group: "19"
    speed: "400G"
    sysport: "153"
    type: "eth"
  - fec: "KPFEC"
    id: "145"
    lanes: "0:8"
    serdes_group: "18"
    speed: "400G"
    sysport: "145"
    type: "eth"
  - fec: "KPFEC"
    id: "137"
    lanes: "0:8"
    serdes_group: "17"
    speed: "400G"
    sysport: "137"
    type: "eth"
  - fec: "KPFEC"
    id: "121"
    lanes: "0:8"
    serdes_group: "15"
    speed: "400G"
    sysport: "121"
    type: "eth"
  - fec: "KPFEC"
    id: "129"
    lanes: "0:8"
    serdes_group: "16"
    speed: "400G"
    sysport: "129"
    type: "eth"
  - fec: "KPFEC"
    id: "113"
    lanes: "0:8"
    serdes_group: "14"
    speed: "400G"
    sysport: "113"
    type: "eth"
  - fec: "KPFEC"
    id: "105"
    lanes: "0:8"
    serdes_group: "13"
    speed: "400G"
    sysport: "105"
    type: "eth"
  - fec: "KPFEC"
    id: "97"
    lanes: "0:8"
    serdes_group: "12"
    speed: "400G"
    sysport: "97"
    type: "eth"
  - fec: "KPFEC"
    id: "89"
    lanes: "0:8"
    serdes_group: "11"
    speed: "400G"
    sysport: "89"
    type: "eth"
  - fec: "KPFEC"
    id: "81"
    lanes: "0:8"
    serdes_group: "10"
    speed: "400G"
    sysport: "81"
    type: "eth"
  - fec: "KPFEC"
    id: "73"
    lanes: "0:8"
    serdes_group: "9"
    speed: "400G"
    sysport: "73"
    type: "eth"
  - fec: "KPFEC"
    id: "65"
    lanes: "0:8"
    serdes_group: "8"
    speed: "400G"
    sysport: "65"
    type: "eth"
  - fec: "KPFEC"
    id: "57"
    lanes: "0:8"
    serdes_group: "7"
    speed: "400G"
    sysport: "57"
    type: "eth"
  - fec: "KPFEC"
    id: "49"
    lanes: "0:8"
    serdes_group: "6"
    speed: "400G"
    sysport: "49"
    type: "eth"
  - fec: "KPFEC"
    id: "41"
    lanes: "0:8"
    serdes_group: "5"
    speed: "400G"
    sysport: "41"
    type: "eth"
  - fec: "KPFEC"
    id: "33"
    lanes: "0:8"
    serdes_group: "4"
    speed: "400G"
    sysport: "33"
    type: "eth"
  - fec: "KPFEC"
    id: "25"
    lanes: "0:8"
    serdes_group: "3"
    speed: "400G"
    sysport: "25"
    type: "eth"
  - fec: "KPFEC"
    id: "17"
    lanes: "0:8"
    serdes_group: "2"
    speed: "400G"
    sysport: "17"
    type: "eth"
  - fec: "KPFEC"
    id: "9"
    lanes: "0:8"
    serdes_group: "1"
    speed: "400G"
    sysport: "9"
    type: "eth"
  - fec: "KPFEC"
    id: "1"
    lanes: "0:8"
    serdes_group: "0"
    speed: "400G"
    sysport: "1"
    type: "eth"
  isg:
  - id: "0"
    tx_polarity: "00000000"
    rx_polarity: "00000000"
    lane_swap: "64752031"
  - id: "1"
    tx_polarity: "00000000"
    rx_polarity: "00000000"
    lane_swap: "64752031"
  - id: "2"
    tx_polarity: "00000000"
    rx_polarity: "00000000"
    lane_swap: "64752301"
  - id: "3"
    tx_polarity: "00000000"
    rx_polarity: "00000000"
    lane_swap: "74653021"
  - id: "4"
    tx_polarity: "00000000"
    rx_polarity: "00000000"
    lane_swap: "74653021"
  - id: "5"
    tx_polarity: "00000000"
    rx_polarity: "00000000"
    lane_swap: "74653021"
  - id: "6"
    tx_polarity: "00000111"
    rx_polarity: "11001101"
    lane_swap: "30472156"
  - id: "7"
    tx_polarity: "00001001"
    rx_polarity: "01001001"
    lane_swap: "05271436"
  - id: "8"
    tx_polarity: "00000011"
    rx_polarity: "11001100"
    lane_swap: "30472156"
  - id: "9"
    tx_polarity: "10001011"
    rx_polarity: "01001101"
    lane_swap: "05271436"
  - id: "10"
    tx_polarity: "00111111"
    rx_polarity: "11101001"
    lane_swap: "30472156"
  - id: "11"
    tx_polarity: "10111010"
    rx_polarity: "00010110"
    lane_swap: "05271436"
  - id: "12"
    tx_polarity: "01000001"
    rx_polarity: "11010100"
    lane_swap: "30472156"
  - id: "13"
    tx_polarity: "11001001"
    rx_polarity: "01001010"
    lane_swap: "37164520"
  - id: "14"
    tx_polarity: "00000000"
    rx_polarity: "01100111"
    lane_swap: "30472156"
  - id: "15"
    tx_polarity: "00000001"
    rx_polarity: "00001100"
    lane_swap: "30472156"
  - id: "16"
    tx_polarity: "01111111"
    rx_polarity: "00010000"
    lane_swap: "47305621"
  - id: "17"
    tx_polarity: "00001110"
    rx_polarity: "11101101"
    lane_swap: "05271436"
  - id: "18"
    tx_polarity: "00001011"
    rx_polarity: "00001000"
    lane_swap: "30472156"
  - id: "19"
    tx_polarity: "00100010"
    rx_polarity: "01110101"
    lane_swap: "03651274"
  - id: "20"
    tx_polarity: "00010000"
    rx_polarity: "01000001"
    lane_swap: "30472156"
  - id: "21"
    tx_polarity: "00101000"
    rx_polarity: "10010010"
    lane_swap: "31452067"
  - id: "22"
    tx_polarity: "00000000"
    rx_polarity: "10000000"
    lane_swap: "30472156"
  - id: "23"
    tx_polarity: "10001010"
    rx_polarity: "00011001"
    lane_swap: "07251436"
  - id: "24"
    tx_polarity: "00000000"
    rx_polarity: "10111011"
    lane_swap: "30472156"
  - id: "25"
    tx_polarity: "11101001"
    rx_polarity: "00001000"
    lane_swap: "05271436"
  - id: "26"
    tx_polarity: "00000000"
    rx_polarity: "00000000"
    lane_swap: "74563012"
  - id: "27"
    tx_polarity: "00000000"
    rx_polarity: "00000000"
    lane_swap: "75643012"
  - id: "28"
    tx_polarity: "00000000"
    rx_polarity: "00000000"
    lane_swap: "74653021"
  - id: "29"
    tx_polarity: "00000000"
    rx_polarity: "00000000"
    lane_swap: "74563021"
  - id: "30"
    tx_polarity: "00000000"
    rx_polarity: "00000000"
    lane_swap: "75643120"
  - id: "31"
    tx_polarity: "00000000"
    rx_polarity: "00000000"
    lane_swap: "74653021"
  - id: "32"
    tx_polarity: "00000000"
    rx_polarity: "00000000"
    lane_swap: "01234567"

