CISCO_N9200_PLATFORM_MODULE_VERSION = 1.0

export CISCO_N9200_PLATFORM_MODULE_VERSION

CISCO_N9200_PLATFORM_MODULE = platform-modules-n9200_$(CISCO_N9200_PLATFORM_MODULE_VERSION)_amd64.deb
$(CISCO_N9200_PLATFORM_MODULE)_PATH = $(PLATFORM_PATH)
$(CISCO_N9200_PLATFORM_MODULE)_PLATFORM = x86_64-n3164-r0 x86_64-n3200-r0


CISCO_NBI_PACKAGE = cisco-nbi-package_1.0_amd64.deb
$(CISCO_NBI_PACKAGE)_PATH = $(PLATFORM_PATH)

SONIC_COPY_DEBS += $(CISCO_N9200_PLATFORM_MODULE) $(CISCO_NBI_PACKAGE)
SONIC_STRETCH_DEBS += $(CISCO_N9200_PLATFORM_MODULE) $(CISCO_NBI_PACKAGE)

# SONIC_PLATFORM_API_PY2 package
SONIC_PLATFORM_API_PY2 = sonic_platform-1.0-py2-none-any.whl
$(SONIC_PLATFORM_API_PY2)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-cisco/sonic-platform
$(SONIC_PLATFORM_API_PY2)_PYTHON_VERSION = 2
$(SONIC_PLATFORM_API_PY2)_WHEEL_DEPENDS = $(SONIC_PLATFORM_COMMON_PY2) 
SONIC_PYTHON_WHEELS += $(SONIC_PLATFORM_API_PY2)

export sonic_platform_py2_wheel_path="$(addprefix $(PYTHON_WHEELS_PATH)/,$(SONIC_PLATFORM_API_PY2))"

# SONIC_PLATFORM_API_PY3 package
SONIC_PLATFORM_API_PY3 = sonic_platform-1.0-py3-none-any.whl
$(SONIC_PLATFORM_API_PY3)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-cisco/sonic-platform
$(SONIC_PLATFORM_API_PY3)_PYTHON_VERSION = 3
$(SONIC_PLATFORM_API_PY3)_WHEEL_DEPENDS = $(SONIC_PLATFORM_COMMON_PY3) $(SONIC_PLATFORM_API_PY2)
SONIC_PYTHON_WHEELS += $(SONIC_PLATFORM_API_PY3)

export sonic_platform_py3_wheel_path="$(addprefix $(PYTHON_WHEELS_PATH)/,$(SONIC_PLATFORM_API_PY3))"
