# Cisco platform modules

CISCO_PLATFORM_MODULE_VERSION = 1.0

export CISCO_PLATFORM_MODULE_VERSION

CISCO_PLATFORM_MODULE = platform-modules-n9200_$(CISCO_PLATFORM_MODULE_VERSION)_amd64.deb
$(CISCO_PLATFORM_MODULE)_PATH = $(PLATFORM_PATH)/sonic-platform-modules-cisco


SONIC_COPY_DEBS += $(CISCO_PLATFORM_MODULE)
SONIC_STRETCH_DEBS += $(CISCO_PLATFORM_MODULE)
