SONIC_NETOPS_UTIL_PY2 = sonic_netops_util-1.0-py2-none-any.whl
$(SONIC_NETOPS_UTIL_PY2)_SRC_PATH = $(SRC_PATH)/sonic-netops-util
$(SONIC_NETOPS_UTIL_PY2)_PYTHON_VERSION = 2
$(SONIC_NETOPS_UTIL_PY2)_DEPENDS = $(SWSSSDK_PY2)
$(SONIC_NETOPS_UTIL_PY2)_RDEPENDS = $(SWSSSDK_PY2)

SONIC_PYTHON_WHEELS += $(SONIC_NETOPS_UTIL_PY2)
