SONIC_METRICS_DATA = sonic-metrics-data_1.0-1_all.deb
$(SONIC_METRICS_DATA)_SRC_PATH = $(SRC_PATH)/sonic-metrics-data
$(SONIC_METRICS_DATA)_WHEEL_DEPENDS += $(SONIC_METRICS)
$(SONIC_METRICS_DATA)_RDEPENDS += $(SONIC_METRICS)
SONIC_DPKG_DEBS += $(SONIC_METRICS_DATA)
